<a href="https://colab.research.google.com/github/ReginaMoreno/TallerHC/blob/main/Clase24Oct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:6])
print(arr[4:]) #Imprime de ese número en adelante
print(arr[-3:-1])
print(arr[-1]) #números a la izquierda
print(arr[1:5:2])
print(arr[::2])#para ir de dos en dos
print(arr[0:])#toda la lista
print(arr[:0])#lo anterior a x número

[2 3 4 5 6]
[5 6 7]
[5 6]
7
[2 4]
[1 3 5 7]
[1 2 3 4 5 6 7]
[]


In [7]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,2])

[3 8]


In [13]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:1,2])

[3]


In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,3])

[4 9]


In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0,4])

5


In [16]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:1,2:5])

[[3 4 5]]


In [21]:
arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [22]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 0) #encontrar x

print(x)

(array([1, 3, 5, 7]),)


In [28]:
x = np.array ([1,2,3])
y = np.array ([4,5,6])

suma=x+y
print(f"la suma es {suma}")

la suma es [5 7 9]


In [29]:
x = np.array ([1,2,3])
y = np.array ([4,5,6])

resta=x-y
print(f"la resta es {resta}")

la resta es [-3 -3 -3]


In [30]:
x = np.array ([1,2,3])
y = np.array ([4,5,6])

mult=x*y
print(f"la multiplicación es {mult}") #f es la contradicción de  forma, da un formato

la mult es [ 4 10 18]


In [31]:
x = np.array ([1,2,3])
y = np.array ([4,5,6])

div=x/y
print(f"la división es {div}")

la división es [0.25 0.4  0.5 ]


In [32]:
print(f"número pi = {np.pi}")

número pi = 3.141592653589793


In [33]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos) #sin, cos, tan
print(f"los senos {seno}")
print(f"de los angulos {angulos}")

los senos [0.0000000e+00 1.0000000e+00 1.2246468e-16]
de los angulos [0.         1.57079633 3.14159265]


In [35]:
angulos=np.array([0,np.pi/2,np.pi])
coseno=np.cos(angulos)
print(f"los cosenos {coseno}")
print(f"de los angulos {angulos}")

los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
de los angulos [0.         1.57079633 3.14159265]


In [57]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [58]:
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
matriz=x.reshape(4,2)
matriz


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
x.reshape(-1,1)

array([[0.        ],
       [0.33333333],
       [0.66666667],
       [1.        ]])

In [46]:
x=np.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [51]:
np.random.uniform(0,1,6)


array([0.03014145, 0.38322894, 0.99837193, 0.0276229 , 0.2775365 ,
       0.57355865])

In [55]:
np.random.randint(0,10,size=1)

array([4])

In [76]:
i = 1
while i < 11:
  i=i+1
int(input("Escribe un número del 1 al 10 "))
r=np.random.randint(1,11)
int(input("tu número es:",r))

Escribe un número del 1 al 10 8


TypeError: ignored