<a href="https://colab.research.google.com/github/ReginaMoreno/TallerHC/blob/main/Clase19Oct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [17]:
#funciones igal con [] y con () pero se recomiendan más los ()
arr1 = np.array((1,2,3,4,5))

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
#2D (cuadrado)
#np ayuda a ver de mejor forma las matrices
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
#3D (cubo)
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [20]:
a = np.array(42)
b = np.array([1,2,3,4,5])
#numero de elementos
c = np.array([[1,2,3],[4,5,6]])
#numero de listas y numero de elementos general en cada lista
d = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])

In [21]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2do elemento de la 1er fila", arr[1,0])

2do elemento de la 1er fila 6


In [22]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


In [10]:
[[1,2,3],[4,5,6],[7,8,9]]



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
#usando numpy
matriz = np.array([[1,1,1],[1,1,1],[1,1,1]])
suma = np.sum(matriz)
print(suma)

9


In [14]:
#usando listas:
matriz = [[1,1,1],[1,1,1],[1,1,1]]
suma=0
for fila in matriz:
  suma +=sum(fila)
print(suma)

9


In [27]:
#producto punto
lista1 = [1,2,3]
lista2 = [4,5,6]
productoesc = sum(x*y for x, y in zip(lista1,lista2))
print(productoesc)

32


In [30]:
A=[[1,1,1],[1,1,1],[1,1,1]]

suma=0
for i in range(len(A)):
  for j in range(len(A)):
    suma=suma+A[i][j]
print(f"la suma es {suma}")

la suma es 9


In [32]:
import numpy as np
arr=np.array([[1,1,1],[1,1,1],[1,1,1]])

sumaArr=0.0
for i in range(len(A)):
  for j in range(len(A)):
    sumaArr=sumaArr+arr[i,j]
print(f"la suma es {sumaArr}")

la suma es 9.0


In [40]:
def ProdPunto(a,b):
  #listas
  PP=0.0
  for i in range(len(a)):
    PP=PP+a[i]*b[i]
  return PP

In [41]:
arr2=np.array([[1,1,1],[1,1,1],[1,1,1]])
arr3=np.array([[1,1,1],[1,1,1],[1,1,1]])
Pp_por_reng=np.array([0,0,0])
Pp_por_col=np.array([0,0,0])

for i in range(len(arr2)):
  Pp_por_reng[i]=ProdPunto(arr2[i],arr3[i])

Pp_por_reng

array([3, 3, 3])

In [42]:
def AgarraCol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])

  return np.array(nuevo)

In [43]:
col1=AgarraCol(arr2,0)
col1

array([1, 1, 1])

In [48]:
for i in range(len(arr2)):
 Pp_por_col[i]=ProdPunto(AgarraCol(arr2,i),AgarraCol(arr3,i))

Pp_por_col

array([3, 3, 3])